name: Publish to PyPI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust as needed)
    tags:
      - "v*" # or trigger when create new tag with "v" prefix

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Use a suitable Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        # If your package is not located in the root of your repository, you need to specify the path here.
        # For example, if your package is in a subdirectory called "my_package":
        # package_dir: my_package/

  # Optional: Publish to TestPyPI (for testing purposes)
  publish-to-testpypi:
    runs-on: ubuntu-latest
    # Add condition to prevent duplicate publishing
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'  # Only run on main branch (adjust as needed)
    environment:
      name: testpypi
      url: https://test.pypi.org/p/mcp-weather-server  # Replace with your package name

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          # If your package is not located in the root of your repository, you need to specify the path here.
          # package_dir: my_package/
